# Generated by Django 3.0.6 on 2020-06-10 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gmp_questions',
            fields=[
                ('gmp_questionid', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('compliant', models.SmallIntegerField(null=True)),
                ('fail', models.SmallIntegerField(null=True)),
                ('freetext', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gmp_answers',
            fields=[
                ('gmp_id', models.AutoField(primary_key=True, serialize=False)),
                ('compliant', models.SmallIntegerField(null=True)),
                ('fail', models.SmallIntegerField(null=True)),
                ('freetext', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
