# Generated by Django 3.0.6 on 2020-06-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20200610_1924'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gmp_answers',
        ),
    ]
