# Generated by Django 3.0.6 on 2020-06-15 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_delete_gmp_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gmp_questions',
            old_name='user',
            new_name='user_id',
        ),
    ]
