# Generated by Django 3.0.6 on 2020-06-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_auto_20200602_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_total',
        ),
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.IntegerField(default=200),
        ),
    ]
