# Generated by Django 3.0.6 on 2020-06-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20200603_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='county',
        ),
    ]
