# Generated by Django 3.0.6 on 2020-06-21 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20200615_2336'),
        ('areas', '0002_auto_20200621_2245'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('compliant', models.BooleanField(default=False, verbose_name='Is Compliant?/No Risk')),
                ('freetext', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], max_length=6)),
                ('gmp_question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='gmp_questions', to='questions.Gmp_questions')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='areas.Locations')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'transactions',
            },
        ),
        migrations.DeleteModel(
            name='gmp_questions',
        ),
    ]
