# Generated by Django 3.0.6 on 2020-06-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_remove_gmp_questions_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmp_questions',
            name='compliant',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gmp_questions',
            name='freetext',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
