# Generated by Django 3.0.6 on 2020-06-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auto_20200621_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='freetext',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
