# Generated by Django 3.0.6 on 2020-06-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_auto_20200603_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmp_questions',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gmp_questions',
            name='freetext',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gmp_questions',
            name='gmp_questionid',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
