# Generated by Django 3.0.6 on 2020-06-25 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20200615_2336'),
        ('areas', '0002_auto_20200621_2245'),
        ('audit', '0003_auto_20200625_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='gmp_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gmp_questions', to='questions.Gmp_questions'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='areas.Locations'),
        ),
    ]
