# Generated by Django 3.0.6 on 2020-06-03 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_auto_20200603_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmp_questions',
            name='gmp_questionid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
