# Generated by Django 3.0.6 on 2020-06-03 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auto_20200603_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmp_questions',
            name='area',
        ),
        migrations.RemoveField(
            model_name='gmp_questions',
            name='compliant',
        ),
        migrations.RemoveField(
            model_name='gmp_questions',
            name='freetext',
        ),
    ]
