# Generated by Django 3.0.6 on 2020-06-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_auto_20200603_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=30)),
            ],
        ),
    ]
