# Generated by Django 3.0.6 on 2020-06-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0009_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmp_questions',
            name='compliant',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gmp_questions',
            name='fail',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gmp_questions',
            name='freetext',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
