# Generated by Django 3.0.6 on 2020-06-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0010_auto_20200607_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='gmp_answers',
            fields=[
                ('gmp_id', models.AutoField(primary_key=True, serialize=False)),
                ('compliant', models.SmallIntegerField(null=True)),
                ('fail', models.SmallIntegerField(null=True)),
                ('freetext', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gmp_questions',
            name='compliant',
        ),
        migrations.RemoveField(
            model_name='gmp_questions',
            name='fail',
        ),
        migrations.RemoveField(
            model_name='gmp_questions',
            name='freetext',
        ),
    ]
