# Generated by Django 3.0.6 on 2020-06-09 12:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audit', '0017_auto_20200609_1311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='area',
            new_name='areas',
        ),
    ]
