# Generated by Django 3.0.6 on 2020-06-10 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0018_auto_20200609_1330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='department',
        ),
    ]
