# Generated by Django 3.0.6 on 2020-06-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0019_delete_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='areas',
        ),
    ]
